# Generated by Django 3.1.5 on 2021-02-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_auto_20210202_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
