# Generated by Django 3.1.5 on 2021-02-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_auto_20210203_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='time',
            new_name='create_on',
        ),
    ]
