# Generated by Django 3.1.5 on 2021-02-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0007_auto_20210203_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
